# ! Sketch Build Worker YAML
# ! Author: Janrey Licas | CodexLink
# ! Date Created: 11-22-2019
# * Used for Building NodeMCU v2 Lua ESP8266EX / v3 LoLin / ESP32 Sketch
# * Description: Builds NodeMCU v2 Lua ESP8266EX / v3 LoLin / ESP32 Sketches and Libraries

name: Sketch and Component Build Verifier

on:
  push:
    paths:
    - 'SketchSRC/FLSHF_NodeMCU/**/*.cpp'
    - 'SketchSRC/FLSHF_NodeMCU/**/*.ino'
    - 'SketchSRC/FLSHF_NodeMCU/**/*.h'
    - '**/MSketch_BuildWorker.yml'
    - '**/MSketch_BuildWorker.yaml'

  pull_request:
    paths:
    - 'SketchSRC/FLSHF_NodeMCU/**/*.cpp'
    - 'SketchSRC/FLSHF_NodeMCU/**/*.ino'
    - 'SketchSRC/FLSHF_NodeMCU/**/*.h'
    - '**/MSketch_BuildWorker.yml'
    - '**/MSketch_BuildWorker.yaml'

jobs:
  SketchWorker:
    name: ESP Variant Sketch Build Worker
    runs-on: ubuntu-18.04

    env:
      PARAM_DELIMITER_START: "["
      PARAM_DELIMITER_END: "]"
      PARAM_SEPERATOR: ","
      PARAM_ARGS_DELIMITER: "--"

      IGNORE_RUN_TEST: --IGNORE_COMMIT
      FORCE_EXP: --FORCE_CHECK_EXPERIMENTALS
      FORCE_MAIN: --FORCE_CHECK_MAIN
      FORCE_ALL: --FORCE_CHECK_ALL

    steps:
      - name: Stage 0 | Commit Parameter Checking
        run: echo "TBA"

      - name: Stage 1 | Event Track
        run: echo "TBA"

      - name: Stage 1 | Repository Checkout
        uses: actions/checkout@master

      - name: Stage - | Debug Mode | Dump Actions Info
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}

        run: |
          echo "$GITHUB_CONTEXT"
          echo "$JOB_CONTEXT"
          echo "$STEPS_CONTEXT"
          run: echo "$RUNNER_CONTEXT"

      - name: Stage 2 | Arduino CLI Setup
        uses: arduino/setup-arduino-cli@master

      - name: Stage 3 | Hardware Arch Setup on Arduino CLI
        env:
          mcu_platform_candidate: esp8266:esp8266
          boardAdditionals: https://arduino.esp8266.com/stable/package_esp8266com_index.json

        run: |
          arduino-cli core update-index --additional-urls $boardAdditionals
          arduino-cli core install $mcu_platform_candidate --additional-urls $boardAdditionals

      - name: B.Stage 4 | Sketch Verification
        env:
          mcu_candidate_fqbn: esp8266:esp8266:nodemcuv2
          mcu_platform_sketch:  SketchSRC/FLSHF_NodeMCU/FLSHF_NodeMCU.ino

        run: arduino-cli compile --fqbn $mcu_candidate_fqbn $mcu_platform_sketch