# ! Sketch Build Worker YAML
# ! Author: Janrey Licas | CodexLink
# ! Date Created: 11-22-2019
# * Used for Building NodeMCU v2 Lua ESP8266EX / v3 LoLin / ESP32 Sketch
# * Description: Builds NodeMCU v2 Lua ESP8266EX / v3 LoLin / ESP32 Sketches and Libraries

name: Main Sketch Build Worker

on:
  push:
    paths:
    - 'SketchSRC/FLSHF_NodeMCU/**/*.cpp'
    - 'SketchSRC/FLSHF_NodeMCU/**/*.ino'
    - 'SketchSRC/FLSHF_NodeMCU/**/*.h'
    - '**/SketchBuildWorker.yml'
    - '**/SketchBuildWorker.yaml'

  pull_request:
    paths:
    - 'SketchSRC/FLSHF_NodeMCU/**/*.cpp'
    - 'SketchSRC/FLSHF_NodeMCU/**/*.ino'
    - 'SketchSRC/FLSHF_NodeMCU/**/*.h'
    - '**/SketchBuildWorker.yml'
    - '**/SketchBuildWorker.yaml'

jobs:
  ESP_VariantSketchWorker:
    name: ESP Variant Sketch Build Worker
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        mcu_candidate_fqbn: "esp8266:esp8266:nodemcuv2"

        include:
        - mcu_candidate_fqbn: esp8266:esp8266:nodemcuv2
          mcu_platform_candidate: esp8266:esp8266
          mcu_platform_sketch:  __IoTMesC_SRC/IoTMesC_FSLHFile_NodeMCU/IoTMesC_FSLHFile_NodeMCU.ino
          boardAdditionals: https://arduino.esp8266.com/stable/package_esp8266com_index.json

    steps:
    - name: Stage 1 | Repository Checkout
      uses: actions/checkout@master

    - name: Stage 2 | Arduino CLI Setup
      uses: arduino/setup-arduino-cli@master

    - name: Stage 3 | Hardware Arch Setup on Arduino CLI
      run : |
        arduino-cli core update-index --additional-urls ${{ matrix.boardAdditionals }}
        arduino-cli core install ${{ matrix.mcu_platform_candidate }} --additional-urls ${{ matrix.boardAdditionals }}

    - name: B.Stage 4 | Sketch Verification
      run: arduino-cli compile --fqbn ${{ matrix.mcu_candidate_fqbn }} ${{ matrix.mcu_platform_sketch }}