# !Sketch Build Worker YAML
# ! Author: Janrey Licas | CodexLink
# ! Date Created: 11-22-2019
# * Used for Building NodeMCU and Arduino Sketches
# * Description: Builds both Arduino and NodeMCU Sketches and Libraries
# * for every commit and pull request we do. Without actually trying to do it manually.


name: IoTMesC Sketch Build Worker

on:
  push:
    paths:
    - '**.cpp'
    - '**.ino'
    - '**.h'
    - '**.yml'
    - '**.yaml'

  pull_request:
    paths:
    - '**.cpp'
    - '**.ino'
    - '**.h'
    - '**.yml'
    - '**.yaml'

jobs:

  AVRBuildWorker:
    name: Arduino Sketch Build Worker
    runs-on: windows-latest

    strategy:
      matrix:
        mcu_candidate_fqbn: ["arduino:avr:mega:cpu=atmega2560", "arduino:avr:uno"]

        include:
        - mcu_candidate_fqbn: arduino:avr:mega:cpu=atmega2560
          mcu_platform_candidate: arduino:avr
          mcu_platform_sketch: IoTMesC_AVR_Arduino/IoTMesC_AVR_Arduino.ino

        - mcu_candidate_fqbn: arduino:avr:mega:cpu=atmega2560
          mcu_platform_candidate: arduino:avr
          mcu_platform_sketch: IoTMesC_AVR_Arduino/IoTMesC_AVR_Arduino.ino

    steps:
    - name: A.Stage 1 | Repository Checkout
      uses: actions/checkout@master

    - name: A.Stage 2 | Arduino-CLI Setup
      uses: arduino/setup-arduino-cli@v1.0.0

    - name: A.Stage 3 | Arduino Setup on Arduino-CLI
      run: |
        arduino-cli core update-index
        arduino-cli core install ${{ matrix.mcu_platform_candidate }}

    - name: A.Stage 4 | Sketch Verification
      run: arduino-cli compile --fqbn ${{ matrix.mcu_candidate_fqbn }} /${{ matrix.mcu_platform_sketch }}

  ESPBuildWorker:
    name: NodeMCU Sketch Build Worker
    needs: AVRBuildWorker
    runs-on: windows-latest

    strategy:
      matrix:
        mcu_candidate_fqbn: ["esp8266:esp8266:nodemcu", "esp8266:esp8266:nodemcuv2"]

        include:
        - mcu_candidate_fqbn: esp8266:esp8266:nodemcu
          mcu_platform_candidate: esp8266:esp8266
          mcu_platform_sketch: IoTMesC_ESP_NodeMCU/IoTMesC_ESP_NodeMCU.ino
          boardAdditionals: https://arduino.esp8266.com/stable/package_esp8266com_index.json

        - mcu_candidate_fqbn: esp8266:esp8266:nodemcuv2
          mcu_platform_candidate: esp8266:esp8266
          mcu_platform_sketch: IoTMesC_ESP_NodeMCU/IoTMesC_ESP_NodeMCU.ino
          boardAdditionals: https://arduino.esp8266.com/stable/package_esp8266com_index.json

    steps:
    - name: A.Stage 1 | Repository Checkout
      uses: actions/checkout@master

    - name: A.Stage 2 | Arduino-CLI Setup
      uses: arduino/setup-arduino-cli@v1.0.0

    - name: B.Stage 3 | ESP8266 Setup on Arduino-CLI
      run : |
        arduino-cli core update-index --additional-urls ${{ matrix.boardAdditionals }}
        arduino-cli core install ${{ matrix.mcu_platform_candidate }} --additional-urls ${{ matrix.boardAdditionals }}

    - name: B.Stage 4 | Sketch Verification
      run: arduino-cli compile --fqbn ${{ matrix.mcu_candidate_fqbn }}  /${{ matrix.mcu_platform_sketch }}