# Sketch Build Worker YAML
# Used for Building NodeMCU and Arduino Sketches
#description: Builds both Arduino and NodeMCU Sketches and Libraries for Every commit and pull request we do. Without actually trying to do it manually.
#author: Janrey Licas | CodexLink
#date_created: 11-22-2019

name: IoTMesC Sketch Build Worker

on:
  push:
    paths:
    - '**.cpp'
    - '**.ino'
    - '**.h'
    - '**.yml'
    - '**.yaml'

  pull_request:
    paths:
    - '**.cpp'
    - '**.ino'
    - '**.h'
    - '**.yml'
    - '**.yaml'

jobs:
  BuildWorker:
    name: IoTMesC | Repository Initialization
    runs-on: windows-latest
    timeout-minutes: 60
    env:
      boardAdditionals: http://arduino.esp8266.com/stable/package_esp8266com_index.json

    strategy:
      matrix:
        mcu_platform: ["arduino:avr", "esp8266:esp8266"]
        mcu_fqn_candidate: ["arduino:avr:uno", "arduino:avr:mega:cpu=atmega2560", "esp8266:esp8266:nodemcu", "esp8266:esp8266:nodemcuv2"]

        exclude:
        - mcu_platform: "arduino:avr"
          mcu_fqn_candidate: "arduino:avr:uno", "arduino:avr:mega:cpu=atmega2560"

        - mcu_platform: "esp8266:esp8266"
          mcu_fqn_candidate: "esp8266:esp8266:nodemcu", "esp8266:esp8266:nodemcuv2"

    steps:
    - name: Stage 1 | Repo Checkout
      uses: actions/checkout@v1

    - name: Stage 2.0 | CLI Setup
      uses: arduino/setup-arduino-cli@m1.0.0

    - name: Stage 2.1 | CLI Setup for Arduino Device
      if: matrix.mcu_fqn_candidate == 'arduino:avr:mega:cpu=atmega2560' || matrix.mcu_fqn_candidate == 'arduino:avr:uno'
      run: |
        arduino-cli core update-index
        arduino-cli core install ${{ matrix.mcu_name_candidate }}

    - name: Stage 2.2 | CLI Setup for ESP8266 Devices
      if: matrix.mcu_fqn_candidate == 'esp8266:esp8266:nodemcu' || matrix.mcu_fqn_candidate == 'esp8266:esp8266:nodemcuv2'
      run : |
        arduino-cli core update-index --additional-urls $boardAdditionals
        arduino-cli core install ${{ matrix.mcu_name_candidate }}

  AVRBuildWorker:
    name: Step 3.1 | Arduino Sketch Build Worker
    runs-on: windows-latest
    timeout-minutes: 60
    needs: BuildWorker
    env:
      avrSketch: ./

    steps:
    - name: Arduino Sketch Build Worker | Sketch Verification
      if: matrix.mcu_fqn_candidate == 'arduino:avr:mega:cpu=atmega2560' || matrix.mcu_fqn_candidate == 'arduino:avr:uno'
      run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./$avrSketch

  ESPBuildWorker:
    name: Step 3.2 | NodeMCU Sketch Build Worker | Sketch Verification
    runs-on: windows-latest
    timeout-minutes: 60
    needs: AVRBuildWorker
    env:
      espSketch: ./

    steps:
    - name: NodeMCU Sketch Build Worker | Sketch Verification
      if: matrix.mcu_fqn_candidate == 'esp8266:esp8266:nodemcu' || matrix.mcu_fqn_candidate == 'esp8266:esp8266:nodemcuv2'
      run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./$espSketch